In [106]:
import pandas as pd
import numpy as np

In [2]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 3C26-45E0

 C:\Users\cityo\Desktop\Git_Space\jupyter 디렉터리

2021-09-08  오전 11:27    <DIR>          .
2021-09-08  오전 11:27    <DIR>          ..
2021-09-08  오전 11:12    <DIR>          .ipynb_checkpoints
2021-08-14  오후 03:56           112,258 0814.ipynb
2021-09-07  오후 03:36            38,670 0814-2.ipynb
2021-08-18  오후 03:42           107,784 0818.ipynb
2021-08-02  오후 06:02            62,127 20210802_기계학습_03_로지스틱 회귀.ipynb
2021-08-05  오후 02:59            44,466 20210805_자연어처리_01_토큰화(tokenization).ipynb
2021-08-14  오후 04:31           601,582 20210811 - Bus_load_preprocessing.ipynb
2021-08-11  오전 10:09            19,836 210810ReadJSON.ipynb
2021-08-13  오후 06:05        16,244,834 bus_location.csv
2021-08-14  오전 10:26        19,665,982 bus_location2.csv
2021-08-13  오후 06:05            31,092 bus_route.csv
2021-09-02  오후 09:17            42,062 Chapter_14_Web_Scraping.ipynb
2021-09-02  오후 09:17            40,682 Chapter_14_Web_Scraping_ebook.ipynb
2021-09-02  오후 09:17            42,049 Chapter_14_Web_Scraping_printing3.ipynb
2021-09-02  오후 09:17            44,304 Chapter_15_Web_API.ipynb
2021-09-02  오후 09:13            43,978 Chapter_15_Web_API_printing3.ipynb
2021-09-08  오전 09:00    <DIR>          crawling
2021-06-17  오후 09:48            13,703 data analysis web scraping - 210617.ipynb
2021-06-18  오전 01:30             8,365 data analysis web scraping2 - 210618.ipynb
2021-08-17  오전 10:53        10,042,625 data.csv
2021-08-30  오후 11:53               128 descs.npy
2021-08-18  오전 11:49         7,708,719 df_bus_100100073_weather.csv
2021-08-05  오후 08:56         6,997,688 Jeju_analysis_Final.ipynb
2021-09-08  오전 09:00    <DIR>          kafka
2021-08-09  오후 09:49           136,164 matplotlib.pyplot linestyle.ipynb
2021-08-05  오후 08:22           165,675 Music academy in hongdae.ipynb
2021-09-08  오전 08:58    <DIR>          nlp
2021-09-08  오전 09:00    <DIR>          shape_predictor_68_face_landmarks.dat
2021-08-09  오후 03:24            39,073 spark.ipynb
2021-07-31  오전 12:46           452,865 test.csv
2021-08-30  오후 11:52             5,857 Untitled.ipynb
2021-09-08  오전 11:22             7,188 Untitled1.ipynb
2021-08-30  오후 02:19        24,510,355 video.mp4
2021-08-23  오후 04:23            34,213 z.PNG
2021-09-08  오전 11:10    <DIR>          교통
2021-09-02  오후 09:38           107,394 교통데이터_크롤링연습0902.ipynb
2021-09-04  오후 07:22            14,300 구글API.ipynb
2021-08-06  오전 11:30        43,502,858 국토교통부_표준주택가격_20210101.csv
2021-07-15  오후 04:26         7,292,313 김하연_가공데이터.csv
2021-08-05  오후 08:44         7,210,798 김하연_분석-checkpoint.ipynb
2021-09-03  오후 09:51           219,889 데이터_전처리.ipynb
2021-09-07  오후 03:30             8,897 사고구조분석표_발산역앞사거리.xls
2021-09-08  오전 11:27            22,579 사고다발지역 데이터 + 지점명, 위도, 경도.ipynb
2021-06-29  오후 05:58        74,345,173 서울시 우리마을가게 상권분석서비스(상권-추정매출).csv
2021-08-06  오후 01:21       438,109,040 서울특별시 부동산 실거래가 정보.csv
2021-07-06  오전 11:29         6,346,611 서울특별시 학원 교습소정보.csv
2021-08-06  오후 02:11            65,799 아파트 예측 테스트.ipynb
2021-08-06  오후 01:41            11,241 아파트(매매)_실거래가_20210806134151.xlsx
2021-08-05  오후 07:31            67,982 자연어처리_TextClassification_NaverMoviewReview.ipynb
2021-08-18  오후 08:12            93,689 작업물_0817.ipynb
2021-08-18  오후 08:11           316,860 작업물_0818.ipynb
2021-09-08  오전 11:23            26,855 지점명_좌표데이터.csv
2021-09-08  오전 11:23            40,363 지점명_좌표데이터.xlsx
              47개 파일         665,066,965 바이트
               8개 디렉터리  188,397,670,400 바이트 남음

In [7]:
latlng_df = pd.read_excel('지점명_좌표데이터.xlsx')
# latlng_df = latlng_df.iloc[:,1:4]
latlng_df

             지점명         위도          경도
0         수서역사거리  37.487468  127.101325
1       신논현역 사거리  37.501817  127.025606
2    성수대교 남단 사거리  37.537047  127.034935
3     을지병원 앞 사거리  37.519680  127.028133
4        신사역 오거리  37.516287  127.020023
..           ...        ...         ...
559       청계6가 앞  37.569880  127.009631
560  서울메트로 앞 삼거리  37.565473  127.009655
561      동1로지하차도  37.595102  127.080242
562      면목2동사거리  37.586626  127.079933
563      중랑구청사거리  37.606860  127.095233

[564 rows x 3 columns]

In [47]:
for idx, val in latlng_df.iterrows():
    latlng_df['지점명'][idx] = latlng_df['지점명'][idx].replace(' ', '')

C:\Users\cityo\AppData\Local\Temp/ipykernel_5060/2219191369.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  latlng_df['지점명'][idx] = latlng_df['지점명'][idx].replace(' ', '')

In [54]:
latlng_df

           지점명         위도          경도
0       수서역사거리  37.487468  127.101325
1      신논현역사거리  37.501817  127.025606
2    성수대교남단사거리  37.537047  127.034935
3     을지병원앞사거리  37.519680  127.028133
4       신사역오거리  37.516287  127.020023
..         ...        ...         ...
559      청계6가앞  37.569880  127.009631
560  서울메트로앞삼거리  37.565473  127.009655
561    동1로지하차도  37.595102  127.080242
562    면목2동사거리  37.586626  127.079933
563    중랑구청사거리  37.606860  127.095233

[564 rows x 3 columns]

In [49]:
latlng_df.to_csv('C:/Users/cityo/Desktop/united_name.csv' , encoding='utf-8-sig', header=False)

In [6]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 3C26-45E0

 C:\Users\cityo\Desktop\Git_Space\jupyter 디렉터리

2021-09-08  오전 11:03    <DIR>          .
2021-09-08  오전 11:03    <DIR>          ..
2021-09-08  오전 10:29    <DIR>          .ipynb_checkpoints
2021-08-14  오후 03:56           112,258 0814.ipynb
2021-09-07  오후 03:36            38,670 0814-2.ipynb
2021-08-18  오후 03:42           107,784 0818.ipynb
2021-08-02  오후 06:02            62,127 20210802_기계학습_03_로지스틱 회귀.ipynb
2021-08-05  오후 02:59            44,466 20210805_자연어처리_01_토큰화(tokenization).ipynb
2021-08-14  오후 04:31           601,582 20210811 - Bus_load_preprocessing.ipynb
2021-08-11  오전 10:09            19,836 210810ReadJSON.ipynb
2021-08-13  오후 06:05        16,244,834 bus_location.csv
2021-08-14  오전 10:26        19,665,982 bus_location2.csv
2021-08-13  오후 06:05            31,092 bus_route.csv
2021-09-02  오후 09:17            42,062 Chapter_14_Web_Scraping.ipynb
2021-09-02  오후 09:17            40,682 Chapter_14_Web_Scraping_ebook.ipynb
2021-09-02  오후 09:17            42,049 Chapter_14_Web_Scraping_printing3.ipynb
2021-09-02  오후 09:17            44,304 Chapter_15_Web_API.ipynb
2021-09-02  오후 09:13            43,978 Chapter_15_Web_API_printing3.ipynb
2021-09-08  오전 09:00    <DIR>          crawling
2021-06-17  오후 09:48            13,703 data analysis web scraping - 210617.ipynb
2021-06-18  오전 01:30             8,365 data analysis web scraping2 - 210618.ipynb
2021-08-17  오전 10:53        10,042,625 data.csv
2021-08-30  오후 11:53               128 descs.npy
2021-08-18  오전 11:49         7,708,719 df_bus_100100073_weather.csv
2021-08-05  오후 08:56         6,997,688 Jeju_analysis_Final.ipynb
2021-09-08  오전 09:00    <DIR>          kafka
2021-08-09  오후 09:49           136,164 matplotlib.pyplot linestyle.ipynb
2021-08-05  오후 08:22           165,675 Music academy in hongdae.ipynb
2021-09-08  오전 08:58    <DIR>          nlp
2021-09-08  오전 09:00    <DIR>          shape_predictor_68_face_landmarks.dat
2021-08-09  오후 03:24            39,073 spark.ipynb
2021-07-31  오전 12:46           452,865 test.csv
2021-08-30  오후 11:52             5,857 Untitled.ipynb
2021-08-30  오후 02:19        24,510,355 video.mp4
2021-08-23  오후 04:23            34,213 z.PNG
2021-09-02  오후 09:38           107,394 교통데이터_크롤링연습0902.ipynb
2021-09-04  오후 07:22            14,300 구글API.ipynb
2021-08-06  오전 11:30        43,502,858 국토교통부_표준주택가격_20210101.csv
2021-07-15  오후 04:26         7,292,313 김하연_가공데이터.csv
2021-08-05  오후 08:44         7,210,798 김하연_분석-checkpoint.ipynb
2021-09-03  오후 09:51           219,889 데이터_전처리.ipynb
2021-09-07  오후 03:30             8,897 사고구조분석표_발산역앞사거리.xls
2021-09-08  오전 11:03            14,700 사고다발지역 데이터 + 지점명, 위도, 경도.ipynb
2021-06-29  오후 05:58        74,345,173 서울시 우리마을가게 상권분석서비스(상권-추정매출).csv
2021-08-06  오후 01:21       438,109,040 서울특별시 부동산 실거래가 정보.csv
2021-07-06  오전 11:29         6,346,611 서울특별시 학원 교습소정보.csv
2021-08-06  오후 02:11            65,799 아파트 예측 테스트.ipynb
2021-08-06  오후 01:41            11,241 아파트(매매)_실거래가_20210806134151.xlsx
2021-08-05  오후 07:31            67,982 자연어처리_TextClassification_NaverMoviewReview.ipynb
2021-08-18  오후 08:12            93,689 작업물_0817.ipynb
2021-08-18  오후 08:11           316,860 작업물_0818.ipynb
2021-09-08  오전 09:00    <DIR>          ㅋㅋ
              44개 파일         664,984,680 바이트
               8개 디렉터리  188,558,839,808 바이트 남음

In [91]:
import pandas as pd  
import numpy as np  
import glob  
import os

In [114]:
globbed_files = glob.glob("C:/Users/cityo/Desktop/강서구/올빼미/*.xls")

In [115]:
globbed_files

['C:/Users/cityo/Desktop/강서구/올빼미\\강서구_강서그랜드아이파크앞사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_개화사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_개화역사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_김포공항입구사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_까치산역사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_등촌역삼거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_마곡역부근사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_발산역부근.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_발산역앞사거리.xls',
 'C:/Users/cityo/Desktop/강서구/올빼미\\강서구_서울양동초삼거리.xls']

In [116]:
for file in globbed_files:
    frame = pd.read_excel(file)
    file_name = os.path.basename(file)

In [17]:
# import os

# for file in globbed_files:
#     frame = pd.read_excel(file)
#     file_name = os.path.basename(file)     # os.path.basename(path) : 입력받은 경로의 기본 이름을 반환
    
#     #print('filename:',file_name)
    
#     if file_name.find('(') != -1:
#         idx = file_name.find('(')
#         file_name = file_name[:idx]
#     file_name = file_name.replace('.xls', '')
    
#     idx2 = file_name.find('_')
#     file_name = file_name[idx2 + 1:]

In [110]:
file_name

'강북구_수유역사거리.xls'

In [19]:
frame

,사고구조분석표,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,일련번호,년도,월,일,요일,시각,사고등급,사망자수,중상자수,경상자수,...,NaN,관련자2,사고형태,기상상태,일광상태,사고유형1,사고유형2,법규위반,도로종류,ACC_NO
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,용도,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2017,02,11,토요일,11,경상사고,0,0,1,...,비사업용,이륜,기타사고,맑음,주간,차대차,차대차-기타,안전거리미확보,특별광역시도,NaN
3,2,2017,05,12,금요일,18,부상사고,0,0,0,...,사업용,자전거,진입회전사고,맑음,출퇴근,차대차,측면직각충돌,안전운전불이행,특별광역시도,NaN
4,3,2017,06,08,목요일,09,중상사고,0,1,0,...,사업용,자전거,기타사고,맑음,주간,차대차,차대차-기타,안전운전불이행,특별광역시도,NaN
5,4,2017,06,27,화요일,19,경상사고,0,0,2,...,비사업용,이륜,진입회전사고,흐림,출퇴근,차대차,측면직각충돌,안전운전불이행,특별광역시도,NaN
6,5,2017,07,13,목요일,19,중상사고,0,1,0,...,기타,보행자,진입회전사고,맑음,출퇴근,차대사람,횡단중,신호위반,특별광역시도,NaN
7,6,2017,09,05,화요일,17,중상사고,0,2,1,...,사업용,기타,기타사고,맑음,주간,차량단독,차량단독-기타,데이터없음,특별광역시도,NaN
8,7,2017,09,26,화요일,22,경상사고,0,0,1,...,비사업용,화물,진입회전사고,맑음,심야,차대차,측면직각충돌,안전운전불이행,특별광역시도,NaN
9,8,2018,04,04,수요일,05,중상사고,0,1,0,...,사업용,보행자,진입회전사고,맑음,새벽,차대사람,보도통행중,신호위반,특별광역시도,NaN
10,9,2018,04,12,목요일,13,중상사고,0,1,0,...,비사업용,이륜,기타사고,맑음,주간,차대차,차대차-기타,안전거리미확보,특별광역시도,NaN
11,10,2018,05,25,금요일,14,중상사고,0,2,0,...,사업용,이륜,진입회전사고,맑음,주간,차대차,측면직각충돌,신호위반,특별광역시도,NaN
12,11,2018,08,26,일요일,13,중상사고,0,1,4,...,비사업용,승용,진입회전사고,맑음,주간,차대차,측면직각충돌,안전거리미확보,특별광역시도,NaN
13,12,2018,09,18,화요일,08,경상사고,0,0,1,...,비사업용,승용,기타사고,맑음,출퇴근,차대차,차대차-기타,안전운전불이행,특별광역시도,NaN
14,13,2018,10,13,토요일,07,경상사고,0,0,1,...,사업용,기타,일직선사고,맑음,출퇴근,차대차,추돌(진행중),안전운전불이행,특별광역시도,NaN
15,14,2018,11,01,목요일,13,경상사고,0,0,2,...,기타,이륜,일직선사고,맑음,주간,차대차,추돌(진행중),안전운전불이행,특별광역시도,NaN
16,15,2019,05,10,금요일,10,경상사고,0,0,2,...,비사업용,화물,일직선사고,맑음,주간,차대차,추돌(진행중),안전운전불이행,특별광역시도,NaN
17,16,2019,05,03,금요일,14,경상사고,0,0,1,...,비사업용,승용,진입회전사고,맑음,주간,차대차,측면직각충돌,안전운전불이행,특별광역시도,NaN
18,17,2019,06,02,일요일,20,경상사고,0,0,2,...,비사업용,승용,진입회전사고,맑음,출퇴근,차대차,측면직각충돌,신호위반,특별광역시도,NaN
19,18,2019,07,15,월요일,17,경상사고,0,0,1,...,비사업용,이륜,진입회전사고,맑음,주간,차대차,측면직각충돌,안전운전불이행,특별광역시도,NaN
20,19,2019,11,22,금요일,16,부상사고,0,0,0,...,비사업용,이륜,진입회전사고,맑음,주간,차대차,정면충돌,신호위반,특별광역시도,NaN

In [74]:
file_namena=file_name.split('_')

In [75]:
file_gu=file_namena[0]
file_jang=file_namena[1]

In [76]:
file_jang=file_jang[:-4]

In [77]:
file_jang

'화양사거리'

In [27]:
# import os

# for file in globbed_files:
#     frame = pd.read_excel(file)
#     file_name = os.path.basename(file)

In [118]:
import os

for file in globbed_files:
    frame = pd.read_excel(file)
    file_name = os.path.basename(file)     # os.path.basename(path) : 입력받은 경로의 기본 이름을 반환
    
    file_namena=file_name.split('_')
    file_gu=file_namena[0]
    file_jang=file_namena[1]
    
    file_jang=file_jang[:-4]
    
#     print('filename:',file_name)
    
#     if file_name.find('(') != -1:
#         idx = file_name.find('(')
#         file_name = file_name[:idx]
#     file_name = file_name.replace('.xls', '')
    
#     idx2 = file_name.find('_')
#     file_name = file_name[idx2 + 1:]
    
#     print('after filename:',file_name)
    
    
    
    frame['지점명'] = file_jang
    frame['지점명'][0] = '지점명'
    frame['지점명'][1] = ''
    
    find = latlng_df.loc[latlng_df['지점명'] == file_jang]
    lat = find['위도'].values[0]
    lng = find['경도'].values[0]
    
    frame['위도'] = lat
    frame['위도'][0] = '위도'
    frame['위도'][1] = ''
    
    frame['경도'] = lng
    frame['경도'][0] = '경도'
    frame['경도'][1] = ''
    frame['자치구'] = '강북구'
    frame.to_csv('C:/Users/cityo/Desktop/강서구/올빼미/양진이/%s.csv' %file_jang, encoding='utf-8-sig', header=False)

C:\Users\cityo\AppData\Local\Temp/ipykernel_5060/2360410162.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['위도'][0] = '위도'
C:\Users\cityo\AppData\Local\Temp/ipykernel_5060/2360410162.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['경도'][0] = '경도'

In [78]:
file_jang

'화양사거리'

In [79]:
latlng_df[latlng_df['지점명']==file_jang]

       지점명         위도          경도
106  화양사거리  37.548316  127.067461

In [65]:
latlng_df.loc[latlng_df['지점명']==file_jang]

Empty DataFrame
Columns: [지점명, 위도, 경도]
Index: []

In [ ]:
#     frame['지점명'] = file_jang
#     frame['지점명'][0] = '지점명'
#     frame['지점명'][1] = ''
    
    find = latlng_df.loc[latlng_df['지점명'] == file_jang]
    lat = find['위도'].values[0]
    lng = find['경도'].values[0]

In [55]:
latlng_df.head()

         지점명         위도          경도
0     수서역사거리  37.487468  127.101325
1    신논현역사거리  37.501817  127.025606
2  성수대교남단사거리  37.537047  127.034935
3   을지병원앞사거리  37.519680  127.028133
4     신사역오거리  37.516287  127.020023

In [81]:
import pandas as pd
import glob
import os

In [113]:
pd.read_csv('C:/Users/cityo/Desktop/광진구/.csv',encoding='cp949')